name: testing_and_building_repo
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Distribution Perl
    steps:
    - uses: actions/checkout@v2 
    - name: Get all git tags
      run: |
          git fetch --prune --unshallow --tags --force
          git describe --always
    
   # Caching cpanm external modules 
    - name: Cache cpanm external modules
      id: cpanmCache
      uses: actions/cache@v2
      with:
        path: ~/perl5ext  
        key: ${{ runner.os}}-build-cpanm-external
     
    - name: install cpanm 
      run: |
          #installing cpanm
          wget -qO - https://cpanmin.us | /usr/bin/perl - --sudo App::cpanminus

    - name: install system packages 
      run: |
          sudo apt-get update
          sudo apt-get install -qq uuid-dev    # For Perl UUID module
          sudo apt-get install -qq libgd-dev libgd-text-perl # For npg_tracking

    #run the perl install script
    - name: install NPG Perl dependencies, and their CPAN dependencies
      run: |
          cpanm --local-lib=~/perl5ext local::lib && eval $(perl -I ~/perl5ext/lib/perl5/ -Mlocal::lib)
          ${GITHUB_WORKSPACE}/scripts/install_npg_perl_dependencies.sh $WTSI_NPG_GITHUB_URL $WTSI_NPG_BUILD_BRANCH
      env:
        WTSI_NPG_GITHUB_URL: https://github.com/wtsi-npg
        WTSI_NPG_BUILD_BRANCH: ${{ github.base_ref || github.ref }} #getting name of current github branch
    
    # install deps
    - name: install cpanm dependencies
      run: |
          eval $(perl -I ~/perl5ext/lib/perl5/ -Mlocal::lib=~/perl5npg)
          eval $(perl -I ~/perl5ext/lib/perl5/ -Mlocal::lib=~/perl5ext)
          cpanm --installdeps .

    # build
    - name: run Build.PL and ./Build
      run: |
          eval $(perl -I ~/perl5ext/lib/perl5/ -Mlocal::lib=~/perl5ext)
          eval $(perl -I ~/perl5ext/lib/perl5/ -Mlocal::lib=~/perl5npg)
          export TEST_AUTHOR=1
          perl Build.PL && ./Build test --verbose && ./Build install
 
    # Archive logs if failure
    - name: Archive CPAN logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: cpan_log
        path: /home/runner/.cpanm/work/*/build.log
        retention-days: 5
